builds:
  - binary: kubelogin
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  files:
    - none*
brew:
  github:
    owner: int128
    name: homebrew-kubelogin
  homepage: https://github.com/int128/kubelogin
  description: "kubectl with OpenID Connect (OIDC) authentication"
  test: |
    system "#{bin}/kubelogin --help"
    system "#{bin}/kubectl-login --help"
  install: |
    bin.install "kubelogin"
    ln_s bin/"kubelogin", bin/"kubectl-login"
