apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: oidc-login
spec:
  homepage: https://github.com/int128/kubelogin
  shortDescription: kubectl integration for OpenID Connect authentication
  description: |
    Kubelogin integrates browser based authentication with kubectl.
    You do not need to manually set an ID token and refresh token to the kubeconfig.

  caveats: |
    You need to setup the OIDC provider, Kubernetes API server, role binding and kubeconfig.
    See https://github.com/int128/kubelogin for more.

  version: {{ env "VERSION" }}
  platforms:
    - uri: https://github.com/int128/kubelogin/releases/download/{{ env "VERSION" }}/kubelogin_linux_amd64.zip
      sha256: "{{ sha256 .linux_amd64_archive }}"
      bin: kubelogin
      files:
        - from: "kubelogin"
          to: "."
      selector:
        matchLabels:
          os: linux
          arch: amd64
    - uri: https://github.com/int128/kubelogin/releases/download/{{ env "VERSION" }}/kubelogin_darwin_amd64.zip
      sha256: "{{ sha256 .darwin_amd64_archive }}"
      bin: kubelogin
      files:
        - from: "kubelogin"
          to: "."
      selector:
        matchLabels:
          os: darwin
          arch: amd64
    - uri: https://github.com/int128/kubelogin/releases/download/{{ env "VERSION" }}/kubelogin_windows_amd64.zip
      sha256: "{{ sha256 .windows_amd64_archive }}"
      bin: kubelogin.exe
      files:
        - from: "kubelogin.exe"
          to: "."
      selector:
        matchLabels:
          os: windows
          arch: amd64
