version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/int128/kubelogin
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get -u golang.org/x/lint/golint
      - run: golint
      - run: go build -v
      - run: make -C e2e/authserver/testdata
      - run: go test -v ./...

  release:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/int128/kubelogin
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  all:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - build
