version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: golint
      # Workaround for https://github.com/golang/go/issues/27925
      - run: go get -v k8s.io/client-go
      - run: go vet
      - run: go build -v
      - run: make -C cli_test/authserver/testdata
      - run: go test -v -race ./...

  release:
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - checkout
      # Workaround for https://github.com/golang/go/issues/27925
      - run: go get -v k8s.io/client-go
      - run: go vet
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  all:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - build
